// signupActions
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
// appActions
export const OPEN_SIGN_IN_MODAL = 'OPEN_SIGN_IN_MODAL';
export const CLOSE_SIGN_IN_MODAL = 'CLOSE_SIGN_IN_MODAL';
