// signupActions
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
// appActions
export const OPEN_SIGN_IN_MODAL = 'OPEN_SIGN_IN_MODAL';
export const CLOSE_SIGN_IN_MODAL = 'CLOSE_SIGN_IN_MODAL';
export const OPEN_EVENT_MODAL = 'OPEN_EVENT_MODAL';
export const CLOSE_EVENT_MODAL = 'CLOSE_EVENT_MODAL';
// searchBarActions
export const ADD_TAG_SEARCH_BAR = 'ADD_TAG_SEARCH_BAR';
export const DELETE_TAG_SEARCH_BAR = 'DELETE_TAG_SEARCH_BAR';
export const SEARCH_WITH_SEARCH_BAR_FULFILLED = 'SEARCH_WITH_SEARCH_BAR_FULFILLED';
export const SEARCH_WITH_SEARCH_BAR_REJECTED = 'SEARCH_WITH_SEARCH_BAR_REJECTED';
export const FETCH_SUGGESTTAGS_SEARCH_BAR = 'FETCH_SUGGESTTAGS_SEARCH_BAR';
export const FETCH_EVENTS_FULFILLED = 'FETCH_EVENTS_FULFILLED';
export const FETCH_EVENTS_REJECTED = 'FETCH_EVENTS_REJECTED';
// User actions
export const FETCH_SIGNUP_REQUEST = 'FETCH_SIGNUP_REQUEST';


